spring:
  application:
    name: kotlin-demo
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/testdb2
    username: root
    password: root
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql